/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuickstartRouteImport } from './routes/quickstart'
import { Route as IntroductionRouteImport } from './routes/introduction'
import { Route as InstallRouteImport } from './routes/install'
import { Route as ConceptsRouteImport } from './routes/concepts'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SelfHostingOverviewRouteImport } from './routes/self-hosting/overview'
import { Route as SelfHostingFlyRouteImport } from './routes/self-hosting/fly'
import { Route as SelfHostingEnvironmentRouteImport } from './routes/self-hosting/environment'
import { Route as SelfHostingDockerRouteImport } from './routes/self-hosting/docker'
import { Route as SelfHostingArchitectureRouteImport } from './routes/self-hosting/architecture'
import { Route as SdksTypescriptRouteImport } from './routes/sdks/typescript'
import { Route as SdksRustRouteImport } from './routes/sdks/rust'
import { Route as SdksRestRouteImport } from './routes/sdks/rest'
import { Route as SdksPythonRouteImport } from './routes/sdks/python'
import { Route as PlatformRoadmapRouteImport } from './routes/platform/roadmap'
import { Route as PlatformOverviewRouteImport } from './routes/platform/overview'
import { Route as PlatformNodesRouteImport } from './routes/platform/nodes'
import { Route as PlatformNetworkRouteImport } from './routes/platform/network'
import { Route as PlatformMarketplaceRouteImport } from './routes/platform/marketplace'
import { Route as PlatformEconomicsRouteImport } from './routes/platform/economics'
import { Route as GuidesWebhooksRouteImport } from './routes/guides/webhooks'
import { Route as GuidesTroubleshootingRouteImport } from './routes/guides/troubleshooting'
import { Route as GuidesSearchRouteImport } from './routes/guides/search'
import { Route as GuidesRealtimeRouteImport } from './routes/guides/realtime'
import { Route as GuidesModelsRouteImport } from './routes/guides/models'
import { Route as GuidesFirstAgentRouteImport } from './routes/guides/first-agent'
import { Route as GuidesFaqRouteImport } from './routes/guides/faq'
import { Route as GuidesCliRouteImport } from './routes/guides/cli'
import { Route as ApiReferenceWebhooksRouteImport } from './routes/api-reference/webhooks'
import { Route as ApiReferenceUsageRouteImport } from './routes/api-reference/usage'
import { Route as ApiReferenceSearchRouteImport } from './routes/api-reference/search'
import { Route as ApiReferenceRunsRouteImport } from './routes/api-reference/runs'
import { Route as ApiReferenceRealtimeRouteImport } from './routes/api-reference/realtime'
import { Route as ApiReferenceKeysRouteImport } from './routes/api-reference/keys'
import { Route as ApiReferenceComplianceRouteImport } from './routes/api-reference/compliance'
import { Route as ApiReferenceAuthenticationRouteImport } from './routes/api-reference/authentication'
import { Route as ApiReferenceAgentsRouteImport } from './routes/api-reference/agents'

const QuickstartRoute = QuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroductionRoute = IntroductionRouteImport.update({
  id: '/introduction',
  path: '/introduction',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsRoute = ConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfHostingOverviewRoute = SelfHostingOverviewRouteImport.update({
  id: '/self-hosting/overview',
  path: '/self-hosting/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfHostingFlyRoute = SelfHostingFlyRouteImport.update({
  id: '/self-hosting/fly',
  path: '/self-hosting/fly',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfHostingEnvironmentRoute = SelfHostingEnvironmentRouteImport.update({
  id: '/self-hosting/environment',
  path: '/self-hosting/environment',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfHostingDockerRoute = SelfHostingDockerRouteImport.update({
  id: '/self-hosting/docker',
  path: '/self-hosting/docker',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfHostingArchitectureRoute = SelfHostingArchitectureRouteImport.update({
  id: '/self-hosting/architecture',
  path: '/self-hosting/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const SdksTypescriptRoute = SdksTypescriptRouteImport.update({
  id: '/sdks/typescript',
  path: '/sdks/typescript',
  getParentRoute: () => rootRouteImport,
} as any)
const SdksRustRoute = SdksRustRouteImport.update({
  id: '/sdks/rust',
  path: '/sdks/rust',
  getParentRoute: () => rootRouteImport,
} as any)
const SdksRestRoute = SdksRestRouteImport.update({
  id: '/sdks/rest',
  path: '/sdks/rest',
  getParentRoute: () => rootRouteImport,
} as any)
const SdksPythonRoute = SdksPythonRouteImport.update({
  id: '/sdks/python',
  path: '/sdks/python',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoadmapRoute = PlatformRoadmapRouteImport.update({
  id: '/platform/roadmap',
  path: '/platform/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformOverviewRoute = PlatformOverviewRouteImport.update({
  id: '/platform/overview',
  path: '/platform/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformNodesRoute = PlatformNodesRouteImport.update({
  id: '/platform/nodes',
  path: '/platform/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformNetworkRoute = PlatformNetworkRouteImport.update({
  id: '/platform/network',
  path: '/platform/network',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformMarketplaceRoute = PlatformMarketplaceRouteImport.update({
  id: '/platform/marketplace',
  path: '/platform/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformEconomicsRoute = PlatformEconomicsRouteImport.update({
  id: '/platform/economics',
  path: '/platform/economics',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesWebhooksRoute = GuidesWebhooksRouteImport.update({
  id: '/guides/webhooks',
  path: '/guides/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesTroubleshootingRoute = GuidesTroubleshootingRouteImport.update({
  id: '/guides/troubleshooting',
  path: '/guides/troubleshooting',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSearchRoute = GuidesSearchRouteImport.update({
  id: '/guides/search',
  path: '/guides/search',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRealtimeRoute = GuidesRealtimeRouteImport.update({
  id: '/guides/realtime',
  path: '/guides/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesModelsRoute = GuidesModelsRouteImport.update({
  id: '/guides/models',
  path: '/guides/models',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesFirstAgentRoute = GuidesFirstAgentRouteImport.update({
  id: '/guides/first-agent',
  path: '/guides/first-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesFaqRoute = GuidesFaqRouteImport.update({
  id: '/guides/faq',
  path: '/guides/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesCliRoute = GuidesCliRouteImport.update({
  id: '/guides/cli',
  path: '/guides/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceWebhooksRoute = ApiReferenceWebhooksRouteImport.update({
  id: '/api-reference/webhooks',
  path: '/api-reference/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceUsageRoute = ApiReferenceUsageRouteImport.update({
  id: '/api-reference/usage',
  path: '/api-reference/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceSearchRoute = ApiReferenceSearchRouteImport.update({
  id: '/api-reference/search',
  path: '/api-reference/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRunsRoute = ApiReferenceRunsRouteImport.update({
  id: '/api-reference/runs',
  path: '/api-reference/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRealtimeRoute = ApiReferenceRealtimeRouteImport.update({
  id: '/api-reference/realtime',
  path: '/api-reference/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceKeysRoute = ApiReferenceKeysRouteImport.update({
  id: '/api-reference/keys',
  path: '/api-reference/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceComplianceRoute = ApiReferenceComplianceRouteImport.update({
  id: '/api-reference/compliance',
  path: '/api-reference/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceAuthenticationRoute =
  ApiReferenceAuthenticationRouteImport.update({
    id: '/api-reference/authentication',
    path: '/api-reference/authentication',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiReferenceAgentsRoute = ApiReferenceAgentsRouteImport.update({
  id: '/api-reference/agents',
  path: '/api-reference/agents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/concepts': typeof ConceptsRoute
  '/install': typeof InstallRoute
  '/introduction': typeof IntroductionRoute
  '/quickstart': typeof QuickstartRoute
  '/api-reference/agents': typeof ApiReferenceAgentsRoute
  '/api-reference/authentication': typeof ApiReferenceAuthenticationRoute
  '/api-reference/compliance': typeof ApiReferenceComplianceRoute
  '/api-reference/keys': typeof ApiReferenceKeysRoute
  '/api-reference/realtime': typeof ApiReferenceRealtimeRoute
  '/api-reference/runs': typeof ApiReferenceRunsRoute
  '/api-reference/search': typeof ApiReferenceSearchRoute
  '/api-reference/usage': typeof ApiReferenceUsageRoute
  '/api-reference/webhooks': typeof ApiReferenceWebhooksRoute
  '/guides/cli': typeof GuidesCliRoute
  '/guides/faq': typeof GuidesFaqRoute
  '/guides/first-agent': typeof GuidesFirstAgentRoute
  '/guides/models': typeof GuidesModelsRoute
  '/guides/realtime': typeof GuidesRealtimeRoute
  '/guides/search': typeof GuidesSearchRoute
  '/guides/troubleshooting': typeof GuidesTroubleshootingRoute
  '/guides/webhooks': typeof GuidesWebhooksRoute
  '/platform/economics': typeof PlatformEconomicsRoute
  '/platform/marketplace': typeof PlatformMarketplaceRoute
  '/platform/network': typeof PlatformNetworkRoute
  '/platform/nodes': typeof PlatformNodesRoute
  '/platform/overview': typeof PlatformOverviewRoute
  '/platform/roadmap': typeof PlatformRoadmapRoute
  '/sdks/python': typeof SdksPythonRoute
  '/sdks/rest': typeof SdksRestRoute
  '/sdks/rust': typeof SdksRustRoute
  '/sdks/typescript': typeof SdksTypescriptRoute
  '/self-hosting/architecture': typeof SelfHostingArchitectureRoute
  '/self-hosting/docker': typeof SelfHostingDockerRoute
  '/self-hosting/environment': typeof SelfHostingEnvironmentRoute
  '/self-hosting/fly': typeof SelfHostingFlyRoute
  '/self-hosting/overview': typeof SelfHostingOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/concepts': typeof ConceptsRoute
  '/install': typeof InstallRoute
  '/introduction': typeof IntroductionRoute
  '/quickstart': typeof QuickstartRoute
  '/api-reference/agents': typeof ApiReferenceAgentsRoute
  '/api-reference/authentication': typeof ApiReferenceAuthenticationRoute
  '/api-reference/compliance': typeof ApiReferenceComplianceRoute
  '/api-reference/keys': typeof ApiReferenceKeysRoute
  '/api-reference/realtime': typeof ApiReferenceRealtimeRoute
  '/api-reference/runs': typeof ApiReferenceRunsRoute
  '/api-reference/search': typeof ApiReferenceSearchRoute
  '/api-reference/usage': typeof ApiReferenceUsageRoute
  '/api-reference/webhooks': typeof ApiReferenceWebhooksRoute
  '/guides/cli': typeof GuidesCliRoute
  '/guides/faq': typeof GuidesFaqRoute
  '/guides/first-agent': typeof GuidesFirstAgentRoute
  '/guides/models': typeof GuidesModelsRoute
  '/guides/realtime': typeof GuidesRealtimeRoute
  '/guides/search': typeof GuidesSearchRoute
  '/guides/troubleshooting': typeof GuidesTroubleshootingRoute
  '/guides/webhooks': typeof GuidesWebhooksRoute
  '/platform/economics': typeof PlatformEconomicsRoute
  '/platform/marketplace': typeof PlatformMarketplaceRoute
  '/platform/network': typeof PlatformNetworkRoute
  '/platform/nodes': typeof PlatformNodesRoute
  '/platform/overview': typeof PlatformOverviewRoute
  '/platform/roadmap': typeof PlatformRoadmapRoute
  '/sdks/python': typeof SdksPythonRoute
  '/sdks/rest': typeof SdksRestRoute
  '/sdks/rust': typeof SdksRustRoute
  '/sdks/typescript': typeof SdksTypescriptRoute
  '/self-hosting/architecture': typeof SelfHostingArchitectureRoute
  '/self-hosting/docker': typeof SelfHostingDockerRoute
  '/self-hosting/environment': typeof SelfHostingEnvironmentRoute
  '/self-hosting/fly': typeof SelfHostingFlyRoute
  '/self-hosting/overview': typeof SelfHostingOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/concepts': typeof ConceptsRoute
  '/install': typeof InstallRoute
  '/introduction': typeof IntroductionRoute
  '/quickstart': typeof QuickstartRoute
  '/api-reference/agents': typeof ApiReferenceAgentsRoute
  '/api-reference/authentication': typeof ApiReferenceAuthenticationRoute
  '/api-reference/compliance': typeof ApiReferenceComplianceRoute
  '/api-reference/keys': typeof ApiReferenceKeysRoute
  '/api-reference/realtime': typeof ApiReferenceRealtimeRoute
  '/api-reference/runs': typeof ApiReferenceRunsRoute
  '/api-reference/search': typeof ApiReferenceSearchRoute
  '/api-reference/usage': typeof ApiReferenceUsageRoute
  '/api-reference/webhooks': typeof ApiReferenceWebhooksRoute
  '/guides/cli': typeof GuidesCliRoute
  '/guides/faq': typeof GuidesFaqRoute
  '/guides/first-agent': typeof GuidesFirstAgentRoute
  '/guides/models': typeof GuidesModelsRoute
  '/guides/realtime': typeof GuidesRealtimeRoute
  '/guides/search': typeof GuidesSearchRoute
  '/guides/troubleshooting': typeof GuidesTroubleshootingRoute
  '/guides/webhooks': typeof GuidesWebhooksRoute
  '/platform/economics': typeof PlatformEconomicsRoute
  '/platform/marketplace': typeof PlatformMarketplaceRoute
  '/platform/network': typeof PlatformNetworkRoute
  '/platform/nodes': typeof PlatformNodesRoute
  '/platform/overview': typeof PlatformOverviewRoute
  '/platform/roadmap': typeof PlatformRoadmapRoute
  '/sdks/python': typeof SdksPythonRoute
  '/sdks/rest': typeof SdksRestRoute
  '/sdks/rust': typeof SdksRustRoute
  '/sdks/typescript': typeof SdksTypescriptRoute
  '/self-hosting/architecture': typeof SelfHostingArchitectureRoute
  '/self-hosting/docker': typeof SelfHostingDockerRoute
  '/self-hosting/environment': typeof SelfHostingEnvironmentRoute
  '/self-hosting/fly': typeof SelfHostingFlyRoute
  '/self-hosting/overview': typeof SelfHostingOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/concepts'
    | '/install'
    | '/introduction'
    | '/quickstart'
    | '/api-reference/agents'
    | '/api-reference/authentication'
    | '/api-reference/compliance'
    | '/api-reference/keys'
    | '/api-reference/realtime'
    | '/api-reference/runs'
    | '/api-reference/search'
    | '/api-reference/usage'
    | '/api-reference/webhooks'
    | '/guides/cli'
    | '/guides/faq'
    | '/guides/first-agent'
    | '/guides/models'
    | '/guides/realtime'
    | '/guides/search'
    | '/guides/troubleshooting'
    | '/guides/webhooks'
    | '/platform/economics'
    | '/platform/marketplace'
    | '/platform/network'
    | '/platform/nodes'
    | '/platform/overview'
    | '/platform/roadmap'
    | '/sdks/python'
    | '/sdks/rest'
    | '/sdks/rust'
    | '/sdks/typescript'
    | '/self-hosting/architecture'
    | '/self-hosting/docker'
    | '/self-hosting/environment'
    | '/self-hosting/fly'
    | '/self-hosting/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/concepts'
    | '/install'
    | '/introduction'
    | '/quickstart'
    | '/api-reference/agents'
    | '/api-reference/authentication'
    | '/api-reference/compliance'
    | '/api-reference/keys'
    | '/api-reference/realtime'
    | '/api-reference/runs'
    | '/api-reference/search'
    | '/api-reference/usage'
    | '/api-reference/webhooks'
    | '/guides/cli'
    | '/guides/faq'
    | '/guides/first-agent'
    | '/guides/models'
    | '/guides/realtime'
    | '/guides/search'
    | '/guides/troubleshooting'
    | '/guides/webhooks'
    | '/platform/economics'
    | '/platform/marketplace'
    | '/platform/network'
    | '/platform/nodes'
    | '/platform/overview'
    | '/platform/roadmap'
    | '/sdks/python'
    | '/sdks/rest'
    | '/sdks/rust'
    | '/sdks/typescript'
    | '/self-hosting/architecture'
    | '/self-hosting/docker'
    | '/self-hosting/environment'
    | '/self-hosting/fly'
    | '/self-hosting/overview'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/concepts'
    | '/install'
    | '/introduction'
    | '/quickstart'
    | '/api-reference/agents'
    | '/api-reference/authentication'
    | '/api-reference/compliance'
    | '/api-reference/keys'
    | '/api-reference/realtime'
    | '/api-reference/runs'
    | '/api-reference/search'
    | '/api-reference/usage'
    | '/api-reference/webhooks'
    | '/guides/cli'
    | '/guides/faq'
    | '/guides/first-agent'
    | '/guides/models'
    | '/guides/realtime'
    | '/guides/search'
    | '/guides/troubleshooting'
    | '/guides/webhooks'
    | '/platform/economics'
    | '/platform/marketplace'
    | '/platform/network'
    | '/platform/nodes'
    | '/platform/overview'
    | '/platform/roadmap'
    | '/sdks/python'
    | '/sdks/rest'
    | '/sdks/rust'
    | '/sdks/typescript'
    | '/self-hosting/architecture'
    | '/self-hosting/docker'
    | '/self-hosting/environment'
    | '/self-hosting/fly'
    | '/self-hosting/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  ConceptsRoute: typeof ConceptsRoute
  InstallRoute: typeof InstallRoute
  IntroductionRoute: typeof IntroductionRoute
  QuickstartRoute: typeof QuickstartRoute
  ApiReferenceAgentsRoute: typeof ApiReferenceAgentsRoute
  ApiReferenceAuthenticationRoute: typeof ApiReferenceAuthenticationRoute
  ApiReferenceComplianceRoute: typeof ApiReferenceComplianceRoute
  ApiReferenceKeysRoute: typeof ApiReferenceKeysRoute
  ApiReferenceRealtimeRoute: typeof ApiReferenceRealtimeRoute
  ApiReferenceRunsRoute: typeof ApiReferenceRunsRoute
  ApiReferenceSearchRoute: typeof ApiReferenceSearchRoute
  ApiReferenceUsageRoute: typeof ApiReferenceUsageRoute
  ApiReferenceWebhooksRoute: typeof ApiReferenceWebhooksRoute
  GuidesCliRoute: typeof GuidesCliRoute
  GuidesFaqRoute: typeof GuidesFaqRoute
  GuidesFirstAgentRoute: typeof GuidesFirstAgentRoute
  GuidesModelsRoute: typeof GuidesModelsRoute
  GuidesRealtimeRoute: typeof GuidesRealtimeRoute
  GuidesSearchRoute: typeof GuidesSearchRoute
  GuidesTroubleshootingRoute: typeof GuidesTroubleshootingRoute
  GuidesWebhooksRoute: typeof GuidesWebhooksRoute
  PlatformEconomicsRoute: typeof PlatformEconomicsRoute
  PlatformMarketplaceRoute: typeof PlatformMarketplaceRoute
  PlatformNetworkRoute: typeof PlatformNetworkRoute
  PlatformNodesRoute: typeof PlatformNodesRoute
  PlatformOverviewRoute: typeof PlatformOverviewRoute
  PlatformRoadmapRoute: typeof PlatformRoadmapRoute
  SdksPythonRoute: typeof SdksPythonRoute
  SdksRestRoute: typeof SdksRestRoute
  SdksRustRoute: typeof SdksRustRoute
  SdksTypescriptRoute: typeof SdksTypescriptRoute
  SelfHostingArchitectureRoute: typeof SelfHostingArchitectureRoute
  SelfHostingDockerRoute: typeof SelfHostingDockerRoute
  SelfHostingEnvironmentRoute: typeof SelfHostingEnvironmentRoute
  SelfHostingFlyRoute: typeof SelfHostingFlyRoute
  SelfHostingOverviewRoute: typeof SelfHostingOverviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quickstart': {
      id: '/quickstart'
      path: '/quickstart'
      fullPath: '/quickstart'
      preLoaderRoute: typeof QuickstartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/introduction': {
      id: '/introduction'
      path: '/introduction'
      fullPath: '/introduction'
      preLoaderRoute: typeof IntroductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts': {
      id: '/concepts'
      path: '/concepts'
      fullPath: '/concepts'
      preLoaderRoute: typeof ConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-hosting/overview': {
      id: '/self-hosting/overview'
      path: '/self-hosting/overview'
      fullPath: '/self-hosting/overview'
      preLoaderRoute: typeof SelfHostingOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-hosting/fly': {
      id: '/self-hosting/fly'
      path: '/self-hosting/fly'
      fullPath: '/self-hosting/fly'
      preLoaderRoute: typeof SelfHostingFlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-hosting/environment': {
      id: '/self-hosting/environment'
      path: '/self-hosting/environment'
      fullPath: '/self-hosting/environment'
      preLoaderRoute: typeof SelfHostingEnvironmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-hosting/docker': {
      id: '/self-hosting/docker'
      path: '/self-hosting/docker'
      fullPath: '/self-hosting/docker'
      preLoaderRoute: typeof SelfHostingDockerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-hosting/architecture': {
      id: '/self-hosting/architecture'
      path: '/self-hosting/architecture'
      fullPath: '/self-hosting/architecture'
      preLoaderRoute: typeof SelfHostingArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdks/typescript': {
      id: '/sdks/typescript'
      path: '/sdks/typescript'
      fullPath: '/sdks/typescript'
      preLoaderRoute: typeof SdksTypescriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdks/rust': {
      id: '/sdks/rust'
      path: '/sdks/rust'
      fullPath: '/sdks/rust'
      preLoaderRoute: typeof SdksRustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdks/rest': {
      id: '/sdks/rest'
      path: '/sdks/rest'
      fullPath: '/sdks/rest'
      preLoaderRoute: typeof SdksRestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdks/python': {
      id: '/sdks/python'
      path: '/sdks/python'
      fullPath: '/sdks/python'
      preLoaderRoute: typeof SdksPythonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/roadmap': {
      id: '/platform/roadmap'
      path: '/platform/roadmap'
      fullPath: '/platform/roadmap'
      preLoaderRoute: typeof PlatformRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/overview': {
      id: '/platform/overview'
      path: '/platform/overview'
      fullPath: '/platform/overview'
      preLoaderRoute: typeof PlatformOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/nodes': {
      id: '/platform/nodes'
      path: '/platform/nodes'
      fullPath: '/platform/nodes'
      preLoaderRoute: typeof PlatformNodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/network': {
      id: '/platform/network'
      path: '/platform/network'
      fullPath: '/platform/network'
      preLoaderRoute: typeof PlatformNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/marketplace': {
      id: '/platform/marketplace'
      path: '/platform/marketplace'
      fullPath: '/platform/marketplace'
      preLoaderRoute: typeof PlatformMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/economics': {
      id: '/platform/economics'
      path: '/platform/economics'
      fullPath: '/platform/economics'
      preLoaderRoute: typeof PlatformEconomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/webhooks': {
      id: '/guides/webhooks'
      path: '/guides/webhooks'
      fullPath: '/guides/webhooks'
      preLoaderRoute: typeof GuidesWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/troubleshooting': {
      id: '/guides/troubleshooting'
      path: '/guides/troubleshooting'
      fullPath: '/guides/troubleshooting'
      preLoaderRoute: typeof GuidesTroubleshootingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/search': {
      id: '/guides/search'
      path: '/guides/search'
      fullPath: '/guides/search'
      preLoaderRoute: typeof GuidesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/realtime': {
      id: '/guides/realtime'
      path: '/guides/realtime'
      fullPath: '/guides/realtime'
      preLoaderRoute: typeof GuidesRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/models': {
      id: '/guides/models'
      path: '/guides/models'
      fullPath: '/guides/models'
      preLoaderRoute: typeof GuidesModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/first-agent': {
      id: '/guides/first-agent'
      path: '/guides/first-agent'
      fullPath: '/guides/first-agent'
      preLoaderRoute: typeof GuidesFirstAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/faq': {
      id: '/guides/faq'
      path: '/guides/faq'
      fullPath: '/guides/faq'
      preLoaderRoute: typeof GuidesFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/cli': {
      id: '/guides/cli'
      path: '/guides/cli'
      fullPath: '/guides/cli'
      preLoaderRoute: typeof GuidesCliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference/webhooks': {
      id: '/api-reference/webhooks'
      path: '/api-reference/webhooks'
      fullPath: '/api-reference/webhooks'
      preLoaderRoute: typeof ApiReferenceWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference/usage': {
      id: '/api-reference/usage'
      path: '/api-reference/usage'
      fullPath: '/api-reference/usage'
      preLoaderRoute: typeof ApiReferenceUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference/search': {
      id: '/api-reference/search'
      path: '/api-reference/search'
      fullPath: '/api-reference/search'
      preLoaderRoute: typeof ApiReferenceSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference/runs': {
      id: '/api-reference/runs'
      path: '/api-reference/runs'
      fullPath: '/api-reference/runs'
      preLoaderRoute: typeof ApiReferenceRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference/realtime': {
      id: '/api-reference/realtime'
      path: '/api-reference/realtime'
      fullPath: '/api-reference/realtime'
      preLoaderRoute: typeof ApiReferenceRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference/keys': {
      id: '/api-reference/keys'
      path: '/api-reference/keys'
      fullPath: '/api-reference/keys'
      preLoaderRoute: typeof ApiReferenceKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference/compliance': {
      id: '/api-reference/compliance'
      path: '/api-reference/compliance'
      fullPath: '/api-reference/compliance'
      preLoaderRoute: typeof ApiReferenceComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference/authentication': {
      id: '/api-reference/authentication'
      path: '/api-reference/authentication'
      fullPath: '/api-reference/authentication'
      preLoaderRoute: typeof ApiReferenceAuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference/agents': {
      id: '/api-reference/agents'
      path: '/api-reference/agents'
      fullPath: '/api-reference/agents'
      preLoaderRoute: typeof ApiReferenceAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  ConceptsRoute: ConceptsRoute,
  InstallRoute: InstallRoute,
  IntroductionRoute: IntroductionRoute,
  QuickstartRoute: QuickstartRoute,
  ApiReferenceAgentsRoute: ApiReferenceAgentsRoute,
  ApiReferenceAuthenticationRoute: ApiReferenceAuthenticationRoute,
  ApiReferenceComplianceRoute: ApiReferenceComplianceRoute,
  ApiReferenceKeysRoute: ApiReferenceKeysRoute,
  ApiReferenceRealtimeRoute: ApiReferenceRealtimeRoute,
  ApiReferenceRunsRoute: ApiReferenceRunsRoute,
  ApiReferenceSearchRoute: ApiReferenceSearchRoute,
  ApiReferenceUsageRoute: ApiReferenceUsageRoute,
  ApiReferenceWebhooksRoute: ApiReferenceWebhooksRoute,
  GuidesCliRoute: GuidesCliRoute,
  GuidesFaqRoute: GuidesFaqRoute,
  GuidesFirstAgentRoute: GuidesFirstAgentRoute,
  GuidesModelsRoute: GuidesModelsRoute,
  GuidesRealtimeRoute: GuidesRealtimeRoute,
  GuidesSearchRoute: GuidesSearchRoute,
  GuidesTroubleshootingRoute: GuidesTroubleshootingRoute,
  GuidesWebhooksRoute: GuidesWebhooksRoute,
  PlatformEconomicsRoute: PlatformEconomicsRoute,
  PlatformMarketplaceRoute: PlatformMarketplaceRoute,
  PlatformNetworkRoute: PlatformNetworkRoute,
  PlatformNodesRoute: PlatformNodesRoute,
  PlatformOverviewRoute: PlatformOverviewRoute,
  PlatformRoadmapRoute: PlatformRoadmapRoute,
  SdksPythonRoute: SdksPythonRoute,
  SdksRestRoute: SdksRestRoute,
  SdksRustRoute: SdksRustRoute,
  SdksTypescriptRoute: SdksTypescriptRoute,
  SelfHostingArchitectureRoute: SelfHostingArchitectureRoute,
  SelfHostingDockerRoute: SelfHostingDockerRoute,
  SelfHostingEnvironmentRoute: SelfHostingEnvironmentRoute,
  SelfHostingFlyRoute: SelfHostingFlyRoute,
  SelfHostingOverviewRoute: SelfHostingOverviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
