import type { NewPlan } from "../schema/pg/index.js";
import { seedPlans } from "./plans.js";

// Plan data defined inline to avoid a circular dependency:
// @maschina/plans -> @maschina/db -> @maschina/plans
const planData: NewPlan[] = [
  {
    tier: "access",
    name: "Access",
    monthlyAgentExecutions: 50,
    monthlyApiCalls: 500,
    monthlyModelTokens: 0,
    maxAgents: 1,
    maxApiKeys: 0,
    maxTeamMembers: 1,
    maxConnectors: 1,
    storageGb: 1,
    features: {
      localExecution: true,
      cloudExecution: false,
      maschinaModel: false,
      marketplace: false,
      analytics: false,
      compliance: false,
      prioritySupport: false,
      customConnectors: false,
      webhooks: false,
      sla: false,
      onPrem: false,
      dedicatedInfra: false,
      rbac: false,
      sharedAgentPool: false,
      workflowAutomation: false,
      teamDashboard: false,
    },
  },
  {
    tier: "m1",
    name: "Mach-1",
    monthlyAgentExecutions: 500,
    monthlyApiCalls: 5000,
    monthlyModelTokens: 500000,
    maxAgents: 3,
    maxApiKeys: 3,
    maxTeamMembers: 1,
    maxConnectors: 3,
    storageGb: 5,
    features: {
      localExecution: true,
      cloudExecution: true,
      maschinaModel: true,
      marketplace: true,
      analytics: false,
      compliance: false,
      prioritySupport: false,
      customConnectors: false,
      webhooks: true,
      sla: false,
      onPrem: false,
      dedicatedInfra: false,
      rbac: false,
      sharedAgentPool: false,
      workflowAutomation: false,
      teamDashboard: false,
    },
  },
  {
    tier: "m5",
    name: "Mach-5",
    monthlyAgentExecutions: 2000,
    monthlyApiCalls: 20000,
    monthlyModelTokens: 2000000,
    maxAgents: 10,
    maxApiKeys: 10,
    maxTeamMembers: 1,
    maxConnectors: 10,
    storageGb: 25,
    features: {
      localExecution: true,
      cloudExecution: true,
      maschinaModel: true,
      marketplace: true,
      analytics: true,
      compliance: false,
      prioritySupport: false,
      customConnectors: true,
      webhooks: true,
      sla: false,
      onPrem: false,
      dedicatedInfra: false,
      rbac: false,
      sharedAgentPool: false,
      workflowAutomation: false,
      teamDashboard: false,
    },
  },
  {
    tier: "m10",
    name: "Mach-10",
    monthlyAgentExecutions: 10000,
    monthlyApiCalls: 100000,
    monthlyModelTokens: 10000000,
    maxAgents: 50,
    maxApiKeys: 25,
    maxTeamMembers: 1,
    maxConnectors: 25,
    storageGb: 100,
    features: {
      localExecution: true,
      cloudExecution: true,
      maschinaModel: true,
      marketplace: true,
      analytics: true,
      compliance: true,
      prioritySupport: true,
      customConnectors: true,
      webhooks: true,
      sla: false,
      onPrem: false,
      dedicatedInfra: false,
      rbac: false,
      sharedAgentPool: false,
      workflowAutomation: false,
      teamDashboard: false,
    },
  },
  {
    tier: "teams",
    name: "Mach Team",
    monthlyAgentExecutions: 50000,
    monthlyApiCalls: 500000,
    monthlyModelTokens: 50000000,
    maxAgents: 200,
    maxApiKeys: 100,
    maxTeamMembers: 24,
    maxConnectors: 100,
    storageGb: 500,
    features: {
      localExecution: true,
      cloudExecution: true,
      maschinaModel: true,
      marketplace: true,
      analytics: true,
      compliance: true,
      prioritySupport: true,
      customConnectors: true,
      webhooks: true,
      sla: false,
      onPrem: false,
      dedicatedInfra: false,
      rbac: true,
      sharedAgentPool: true,
      workflowAutomation: true,
      teamDashboard: true,
    },
  },
  {
    tier: "enterprise",
    name: "Enterprise",
    monthlyAgentExecutions: -1,
    monthlyApiCalls: -1,
    monthlyModelTokens: -1,
    maxAgents: -1,
    maxApiKeys: -1,
    maxTeamMembers: -1,
    maxConnectors: -1,
    storageGb: -1,
    features: {
      localExecution: true,
      cloudExecution: true,
      maschinaModel: true,
      marketplace: true,
      analytics: true,
      compliance: true,
      prioritySupport: true,
      customConnectors: true,
      webhooks: true,
      sla: true,
      onPrem: true,
      dedicatedInfra: true,
      rbac: true,
      sharedAgentPool: true,
      workflowAutomation: true,
      teamDashboard: true,
    },
  },
  {
    tier: "internal",
    name: "Internal",
    monthlyAgentExecutions: -1,
    monthlyApiCalls: -1,
    monthlyModelTokens: -1,
    maxAgents: -1,
    maxApiKeys: -1,
    maxTeamMembers: -1,
    maxConnectors: -1,
    storageGb: -1,
    features: {
      localExecution: true,
      cloudExecution: true,
      maschinaModel: true,
      marketplace: true,
      analytics: true,
      compliance: true,
      prioritySupport: true,
      customConnectors: true,
      webhooks: true,
      sla: true,
      onPrem: true,
      dedicatedInfra: true,
      rbac: true,
      sharedAgentPool: true,
      workflowAutomation: true,
      teamDashboard: true,
    },
  },
];

async function main() {
  console.log("Running database seed...");
  await seedPlans(planData);
  console.log("Seed complete.");
  process.exit(0);
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
